import React, { useState, useEffect } from "react";
import { useSelector } from "react-redux";
import { motion, AnimatePresence } from "framer-motion";
import * as Icons from "lucide-react";
import { Plus, Trash2, RotateCcw } from "lucide-react";
import { InlineEditor } from "../../components/admin/InlineEditor";
import api from "../../api/axios";
import { toast } from "react-toastify";
import SEO from "../../components/site/SEO";

const DEFAULT_SERVICES_LIST = [
    { icon: "Headset", title: "Tour Operator", description: "Expert guidance and personalized itineraries for your perfect getaway." },
    { icon: "PlaneTakeoff", title: "Airline Ticketing", description: "Hassle-free domestic and international flight bookings at the best rates." },
    { icon: "Ship", title: "Cruise Services", description: "Luxurious ocean and river cruise packages for unforgettable voyages." },
    { icon: "TrainFront", title: "Railway Ticketing", description: "Quick and confirmed train reservations across the national network." },
    { icon: "Car", title: "Car and Coach Rental", description: "Comfortable and safe road travel with our premium fleet of vehicles." },
    { icon: "Building2", title: "Hotel Booking", description: "Handpicked accommodations ranging from budget stays to luxury resorts." },
    { icon: "BookCheck", title: "Passport and Visa Services", description: "Streamlined documentation and processing for your international travel." },
    { icon: "ShieldCheck", title: "Travel Insurance", description: "Comprehensive coverage to ensure peace of mind throughout your journey." },
    { icon: "MapPin", title: "Destination Advice", description: "Insider knowledge and tips to help you choose your next dream location." }
];

// Helper to render string icon names to actual Lucide components dynamically
const DynamicIcon = ({ name, className, strokeWidth = 1.5 }) => {
    if (!name) return <Icons.HelpCircle className={className} strokeWidth={strokeWidth} />;
    const formattedName = name.charAt(0).toUpperCase() + name.slice(1);
    const Icon = Icons[name] || Icons[formattedName] || Icons.HelpCircle;
    return <Icon className={className} strokeWidth={strokeWidth} />;
};

const defaultSettings = {
    tagline: "What We Offer",
    title: "Our Services",
    servicesList: []
};

// Framer Motion Variants
const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
        opacity: 1,
        transition: { staggerChildren: 0.1, delayChildren: 0.2 }
    }
};

const itemVariants = {
    hidden: { y: 30, opacity: 0 },
    visible: {
        y: 0,
        opacity: 1,
        transition: { type: "spring", stiffness: 100, damping: 15 }
    }
};

export default function Services() {
    const { user, isAuthenticated } = useSelector((state) => state.auth);
    const isSuperAdmin = isAuthenticated && user?.role === "SuperAdmin";

    const [isLoading, setIsLoading] = useState(true);
    const [settings, setSettings] = useState(defaultSettings);
    const [isMobile, setIsMobile] = useState(false);

    // State for the custom confirmation dialog
    const [showRestoreDialog, setShowRestoreDialog] = useState(false);

    useEffect(() => {
        const handleResize = () => setIsMobile(window.innerWidth < 768);
        handleResize();
        window.addEventListener("resize", handleResize);
        return () => window.removeEventListener("resize", handleResize);
    }, []);

    useEffect(() => {
        // ✨ REMOVED document.title from here
        const fetchServicesContent = async () => {
            try {
                const { data } = await api.get("/services");
                if (data) setSettings(data);
            } catch (error) {
                console.error("Failed to fetch services content:", error);
            } finally {
                setIsLoading(false);
            }
        };
        fetchServicesContent();
    }, []);

    const handleCMSFieldSave = async (fieldKey, updatedValue) => {
        // Optimistic UI Update
        setSettings(prev => ({ ...prev, [fieldKey]: updatedValue }));
        try {
            const { data } = await api.put("/services", { [fieldKey]: updatedValue });
            // Sync with backend so we get the real _id generated by Mongoose
            if (data) setSettings(data);
        } catch (error) {
            console.error(`Failed to save ${fieldKey}`);
            toast.error(`Failed to save ${fieldKey}`);
        }
    };

    // Open the custom dialog
    const handleRestoreDefaultsClick = () => {
        setShowRestoreDialog(true);
    };

    // Actually perform the restore logic
    const confirmRestoreDefaults = async () => {
        setShowRestoreDialog(false);

        // 1. Instantly show defaults — no waiting on the network
        setSettings(prev => ({
            ...prev,
            tagline: "What We Offer",
            title: "Our Services",
            servicesList: DEFAULT_SERVICES_LIST
        }));
        toast.success("Services restored to defaults!");

        // 2. Persist on the server in the background, then reconcile real _ids
        try {
            const { data } = await api.put("/services/restore");
            if (data) setSettings(data);
        } catch (error) {
            toast.error("Failed to save restored defaults to the server.");
        }
    };

    const renderEditableText = (fieldKey, type = "text", fallback = "") => {
        const displayValue = settings[fieldKey] || fallback;
        if (isMobile) return <>{displayValue}</>;
        return (
            <InlineEditor
                type={type}
                value={displayValue}
                onSave={(val) => handleCMSFieldSave(fieldKey, val)}
            />
        );
    };

    // --- Dynamic Array Handlers ---
    const updateServicesArray = async (newArray) => {
        // Update locally first for snappiness, then trigger the backend save
        setSettings(prev => ({ ...prev, servicesList: newArray }));
        await handleCMSFieldSave("servicesList", newArray);
    };

    const handleAddService = () => {
        const newService = {
            _id: `temp_${Date.now()}`,
            icon: "Star",
            title: "New Service",
            description: "Description of the new service goes here."
        };
        updateServicesArray([...(settings.servicesList || []), newService]);
    };

    const handleDeleteService = (index) => {
        const currentList = settings.servicesList || [];
        updateServicesArray(currentList.filter((_, i) => i !== index));
    };

    const handleUpdateService = (index, field, value) => {
        const newArray = [...(settings.servicesList || [])];
        newArray[index] = { ...newArray[index], [field]: value };
        updateServicesArray(newArray);
    };

    if (isLoading) {
        return (
            <section className="relative pt-8 pb-20 md:pt-12 bg-[#FDFBF7] overflow-hidden min-h-screen">
                <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-12">
                    {/* Shimmer Header */}
                    <div className="text-center max-w-3xl mx-auto mb-16 flex flex-col items-center">
                        <div className="h-4 w-32 bg-slate-200 rounded animate-pulse mb-4" />
                        <div className="h-12 w-64 md:w-96 bg-slate-200 rounded-lg animate-pulse mb-6" />
                        <div className="w-24 h-1.5 bg-slate-200 mx-auto rounded-full animate-pulse" />
                    </div>

                    {/* Shimmer Grid */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8 lg:gap-10">
                        {[1, 2, 3, 4, 5, 6].map((item) => (
                            <div
                                key={item}
                                className="bg-white rounded-3xl p-8 border border-slate-100 shadow-sm flex flex-col items-center text-center"
                            >
                                {/* Icon shimmer */}
                                <div className="w-20 h-20 rounded-2xl bg-slate-200/70 animate-pulse mb-6" />
                                {/* Title shimmer */}
                                <div className="h-6 w-3/4 bg-slate-200/70 rounded animate-pulse mb-4" />
                                {/* Description shimmer */}
                                <div className="w-full space-y-3 flex flex-col items-center">
                                    <div className="h-3 w-full bg-slate-200/60 rounded animate-pulse" />
                                    <div className="h-3 w-5/6 bg-slate-200/60 rounded animate-pulse" />
                                    <div className="h-3 w-4/6 bg-slate-200/60 rounded animate-pulse" />
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </section>
        );
    }

    return (
        <>
            {/* ✨ NEW SEO COMPONENT ✨ */}
            <SEO
                title={`${settings.title || "Our Services"} | Nepal Trip`}
                description="Explore our wide range of travel services including airline ticketing, hotel bookings, and bespoke Nepal tour operator services."
                url="https://nepaltrip.in/services"
            />

            <section className="relative py-20 bg-[#FDFBF7] overflow-hidden min-h-screen">
                {/* Subtle background decorative elements */}
                <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none">
                    <div className="absolute top-[-20%] left-[-10%] w-[50%] h-[50%] rounded-full bg-[#2A5244]/5 blur-[120px]" />
                    <div className="absolute top-[60%] right-[-10%] w-[40%] h-[60%] rounded-full bg-[#FA6D16]/5 blur-[120px]" />
                </div>

                <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-12">
                    {/* Header Section */}
                    <div className="text-center max-w-3xl mx-auto mb-16">
                        <motion.div
                            initial={{ opacity: 0, y: 10 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            className="text-[#FA6D16] font-bold tracking-wider uppercase text-sm mb-3"
                        >
                            {renderEditableText("tagline", "text", "What We Offer")}
                        </motion.div>
                        <motion.h2
                            initial={{ opacity: 0, y: 10 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: 0.1 }}
                            className="text-4xl md:text-5xl font-black text-[#2A5244] font-serif uppercase tracking-tight"
                        >
                            {renderEditableText("title", "text", "Our Services")}
                        </motion.h2>
                        <div className="w-24 h-1.5 bg-[#FA6D16] mx-auto mt-6 rounded-full" />
                    </div>

                    {/* Services Grid */}
                    <motion.div
                        variants={containerVariants}
                        initial="hidden"
                        whileInView="visible"
                        viewport={{ once: true, margin: "-100px" }}
                        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8 lg:gap-10"
                    >
                        {/* Safeguard with fallback empty array to prevent map crashes */}
                        {(settings.servicesList || []).map((service, idx) => (
                            <motion.div
                                key={service._id || idx}
                                variants={itemVariants}
                                initial="hidden"
                                animate="visible"
                                className="group relative bg-white rounded-3xl p-8 shadow-[0_4px_20px_-4px_rgba(0,0,0,0.05)] border border-slate-100 hover:shadow-[0_8px_30px_-4px_rgba(250,109,22,0.15)] hover:border-[#FA6D16]/30 transition-all duration-300 flex flex-col items-center text-center overflow-hidden"
                            >
                                {/* SuperAdmin Delete Button */}
                                {isSuperAdmin && !isMobile && (
                                    <button
                                        onClick={() => handleDeleteService(idx)}
                                        className="absolute top-4 right-4 text-red-500 opacity-0 group-hover:opacity-100 transition-opacity z-20 hover:scale-110 bg-white rounded-full p-1 shadow-sm"
                                        title="Delete Service"
                                    >
                                        <Trash2 className="h-5 w-5" />
                                    </button>
                                )}

                                {/* Hover background effect */}
                                <div className="absolute inset-0 bg-linear-to-b from-transparent to-[#FA6D16]/5 opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none" />

                                {/* Icon Container */}
                                <div className="relative w-20 h-20 rounded-2xl bg-slate-50 flex flex-col items-center justify-center mb-6 group-hover:scale-110 group-hover:bg-[#FA6D16] group-hover:shadow-lg transition-all duration-500 ease-out z-10 rotate-3 group-hover:rotate-0">
                                    <DynamicIcon name={service.icon || "Star"} className="w-10 h-10 text-[#2A5244] group-hover:text-white transition-colors duration-300" />

                                    {/* SuperAdmin Icon Editor Overlay */}
                                    {isSuperAdmin && !isMobile && (
                                        <div className="absolute -bottom-8 opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap text-xs bg-white text-slate-800 shadow-md border px-2 py-1 rounded">
                                            <InlineEditor
                                                value={service.icon || "Star"}
                                                onSave={(val) => handleUpdateService(idx, "icon", val)}
                                            />
                                        </div>
                                    )}
                                </div>

                                {/* Content */}
                                <div className="relative z-10 w-full">
                                    <h3 className="text-xl font-bold text-slate-800 mb-3 group-hover:text-[#2A5244] transition-colors">
                                        {isMobile ? (service.title || "New Service") : (
                                            <InlineEditor
                                                value={service.title || "New Service"}
                                                onSave={(val) => handleUpdateService(idx, "title", val)}
                                            />
                                        )}
                                    </h3>
                                    <div className="text-sm text-slate-500 leading-relaxed group-hover:text-slate-600 transition-colors">
                                        {isMobile ? (service.description || "Description of the new service goes here.") : (
                                            <InlineEditor
                                                type="textarea"
                                                value={service.description || "Description of the new service goes here."}
                                                onSave={(val) => handleUpdateService(idx, "description", val)}
                                            />
                                        )}
                                    </div>
                                </div>
                            </motion.div>
                        ))}

                        {/* Add New Service Card (SuperAdmin Only) */}
                        {isSuperAdmin && !isMobile && (
                            <div
                                onClick={handleAddService}
                                className="rounded-3xl border-2 border-dashed border-border/60 bg-transparent p-8 flex flex-col items-center justify-center cursor-pointer hover:bg-muted/50 transition-colors opacity-60 hover:opacity-100 min-h-62.5"
                            >
                                <Plus className="h-10 w-10 text-muted-foreground mb-3" />
                                <span className="text-sm font-bold text-muted-foreground">Add New Service</span>
                            </div>
                        )}
                    </motion.div>
                </div>

                {/* Restore Defaults Button (SuperAdmin Only) */}
                {isSuperAdmin && !isMobile && (
                    <div className="absolute bottom-6 right-6 z-50">
                        <button
                            onClick={handleRestoreDefaultsClick}
                            className="flex items-center gap-2 px-4 py-2 bg-white text-slate-600 hover:text-[#FA6D16] hover:bg-orange-50 border border-slate-200 rounded-full shadow-sm hover:shadow-md transition-all duration-300 text-sm font-semibold"
                            title="Reset to default layout"
                        >
                            <RotateCcw className="w-4 h-4" />
                            Restore Defaults
                        </button>
                    </div>
                )}

                {/* Custom Restore Defaults Modal */}
                <AnimatePresence>
                    {showRestoreDialog && (
                        <div className="fixed inset-0 z-100 flex items-center justify-center p-4">
                            {/* Backdrop overlay */}
                            <motion.div
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                exit={{ opacity: 0 }}
                                onClick={() => setShowRestoreDialog(false)}
                                className="absolute inset-0 bg-slate-900/40 backdrop-blur-sm cursor-pointer"
                            />

                            {/* Modal Box */}
                            <motion.div
                                initial={{ opacity: 0, scale: 0.95, y: 20 }}
                                animate={{ opacity: 1, scale: 1, y: 0 }}
                                exit={{ opacity: 0, scale: 0.95, y: 20 }}
                                className="relative w-full max-w-md bg-white rounded-3xl p-8 shadow-2xl overflow-hidden z-10"
                            >
                                {/* Decorative background circle */}
                                <div className="absolute -top-10 -right-10 w-40 h-40 bg-[#FA6D16]/10 rounded-full blur-2xl pointer-events-none" />

                                <div className="flex flex-col items-center text-center relative z-10">
                                    <div className="w-16 h-16 bg-orange-50 text-[#FA6D16] rounded-2xl flex items-center justify-center mb-6 shadow-inner border border-orange-100">
                                        <RotateCcw className="w-8 h-8" />
                                    </div>

                                    <h3 className="text-2xl font-bold text-[#2A5244] mb-3">Restore Defaults?</h3>

                                    <p className="text-slate-500 mb-8 leading-relaxed text-sm">
                                        Are you sure? This will discard your customized changes and reset all services to the original default layout. This action cannot be undone.
                                    </p>

                                    <div className="flex items-center justify-center gap-3 w-full">
                                        <button
                                            onClick={() => setShowRestoreDialog(false)}
                                            className="flex-1 px-6 py-3 rounded-xl bg-slate-100 text-slate-700 font-semibold hover:bg-slate-200 transition-colors"
                                        >
                                            Cancel
                                        </button>
                                        <button
                                            onClick={confirmRestoreDefaults}
                                            className="flex-1 px-6 py-3 rounded-xl bg-[#FA6D16] text-white font-semibold hover:bg-[#e05e10] hover:shadow-lg hover:shadow-[#FA6D16]/20 transition-all"
                                        >
                                            Yes, Restore
                                        </button>
                                    </div>
                                </div>
                            </motion.div>
                        </div>
                    )}
                </AnimatePresence>
            </section>
        </>
    );
}